### ISSUE TITLE
throws error outside editor tab

### ISSUE THREAD

**Issue by oegnus** [tocjent/php-integrator-symbol-viewer#1]
1. installed plugin
2. not in editor tab

**Atom Version**: 1.4.0
**System**: Ubuntu 15.04
**Thrown From**: [php-integrator-symbol-viewer](https://github.com/tocjent/php-integrator-symbol-viewer) package, v0.1.1

### Stack Trace

Uncaught TypeError: editor.getGrammar is not a function

```
At /home/oegnus/.atom/packages/php-integrator-symbol-viewer/lib/Main.js:55

TypeError: editor.getGrammar is not a function
    at updateClassInfo (/home/oegnus/.atom/packages/php-integrator-symbol-viewer/lib/Main.js:55:33)
    at PaneContainer.module.exports.PaneContainer.observeActivePaneItem (/opt/atom/resources/app.asar/src/pane-container.js:145:7)
    at Workspace.module.exports.Workspace.observeActivePaneItem (/opt/atom/resources/app.asar/src/workspace.js:310:33)
    at /home/oegnus/.atom/packages/php-integrator-symbol-viewer/lib/Main.js:82:28
    at /opt/atom/resources/app.asar/node_modules/scandal/node_modules/argparse/node_modules/lodash/lodash.js:2300:43
```

### Commands

```
     -1:45.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:32.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v7.16.1
linter, v1.11.3
php-integrator-annotations, v0.2.3
php-integrator-autocomplete-plus, v0.4.0
php-integrator-base, v0.4.8
php-integrator-navigation, v0.3.0
php-integrator-symbol-viewer, v0.1.1
php-integrator-tooltips, v0.3.0

# Dev
No dev packages
```

**Comment by tocjent** [comment]
Hi, thanks for taking time to report this.

In 0.2.0 release I fixed this by checking if active pane item is an instance of TextEditor. Updating should fix the issue.

I would be glad if you could update the package and close the issue if everything is working.
