### ISSUE TITLE
No longer working after recent updates

### ISSUE THREAD

**Issue by justbane** [tocjent/php-integrator-symbol-viewer#43]
Recent updates (not sure exactly when it disappeared) but the symbol viewer icon is no longer available when it should be. Also, cntrl-shift-J does nothing.

Anyone else having this issue after doing updates recently?

more info - here is the error from the inspector.

```
/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:652 
Error deactivating package 'php-integrator-symbol-viewer' TypeError: Cannot read property 'dispose' of null
    at Object.deactivate (/Users/justbane/.atom/packages/php-integrator-symbol-viewer/lib/Main.js:44:27)
    at Package.module.exports.Package.deactivate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:641:21)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:622:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:337:21
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.pushAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:361:12)
    at Package.module.exports.Package.disable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.disablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:179:16)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:330:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by tarnagas** [comment]
Same issue.

**Comment by justbane** [comment]
I had a friend (who had been on vacation) do the updates step by step from the last couple of days. He found that the symbol-viewer disappeared right after updating php-integrator-base.

**Comment by garetmckinley** [comment]
+1

**Comment by eevargas** [comment]
+1

**Comment by ricpelo** [comment]
+1

**Comment by m-bobrowicz** [comment]
@justbane @tarnagas @garetmckinley @eevargas @ricpelo 

I updated project's README with some info about the situation.
